- name: locale-gen ru_RU.UTF-8
  tags:
  - common
  become: true
  locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: reconfigure locales
  tags:
  - common
  become: true
  command: dpkg-reconfigure -f noninteractive locales

- name: Install software-properties-common 2 enable contrib
  tags:
  - common
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg: [ software-properties-common ]
    state: present

- name: Enable contrib & non-free
  tags:
  - common
  become: true
  shell: "{{ item }}"
  with_items:
  - apt-add-repository contrib
  - apt-add-repository non-free

- name: Install 3rd party utils
  tags:
  - common
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg: [ imagemagick, libgsf-1-114, gnupg2, curl, mlocate, lsb-release, sudo, htop, lsb-release, net-tools ]
    state: present

- name: Update a database for mlocate
  tags:
  - common
  become: true
  command: updatedb
